# -*- coding: utf-8 -*-
"""week 5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jTqzb-fZaxn9OCStMLhrAfB-mza354PA
"""

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelBinarizer

# Prepare data
iris = load_iris(as_frame=True)
X = iris.data
y = (iris.target == 0).astype(int)  # Binary (class 0 vs rest)
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

# ANN Model
model = Sequential()
model.add(Dense(8, input_dim=4, activation='relu'))
model.add(Dense(4, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
history = model.fit(X_train, y_train, epochs=25, batch_size=4, verbose=0)

# Evaluate
loss, acc = model.evaluate(X_test, y_test)
print(f"Test Accuracy: {acc:.2f}")