# -*- coding: utf-8 -*-
"""week 1.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ApJB9YQjf-E6fI7ogm204MUNbx_-kE6j
"""

# Python basics
name = "Rafay"
skills = ["Python", "AI", "ML"]
for skill in skills:
    print("Learning:", skill)

def greet(name):
    return f"Hello, {name}!"
print(greet(name))
# Data Handling
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
data = {
    'Name': ['Ali', 'Sara', 'Usman', 'Zara'],
    'Age': [22, 21, 23, 22],
    'Score': [85, np.nan, 78, 92]
}
df = pd.DataFrame(data)

df['Score'].fillna(df['Score'].mean(), inplace=True)

# Inspect
print(df.describe())
sns.barplot(x='Name', y='Score', data=df)
plt.title("Student Scores")
plt.show()