# -*- coding: utf-8 -*-
"""week 6

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UwwMitCY7UztqMlO7mk8ufl8Qlr6KHfv
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
import joblib

# Load and clean Titanic data
df = pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")
df = df[['Pclass', 'Sex', 'Age', 'Fare', 'Survived']].dropna()
df['Sex'] = df['Sex'].map({'male': 0, 'female': 1})

X = df.drop("Survived", axis=1)
y = df['Survived']
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

# Train and Save
model = RandomForestClassifier()
model.fit(X_train, y_train)
joblib.dump(model, 'titanic_model.pkl')

print("Model trained and saved successfully.")